server:
  port: 8080
  jetty:
    threads:
      max: 150
spring:
  application:
    name: my-test
  kafka:
    consumer:
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        properties:
          spring.json.trusted.packages: '*'
          spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

kafka-topics:
  my-event-topic: my-event-topic